### ISSUE TITLE
Current HEAD Elvish fails on line 197 - use of reserved keyword tmp

### ISSUE THREAD

**Issue by iandol** [zzamboni/elvish-themes#10]
https://github.com/zzamboni/elvish-themes/blob/master/chain.elv#L196

`tmp` is now a reserved keyword: https://github.com/elves/elvish/commit/973fe39798677cf903342b2839ece6d08b8451a0

**Comment by iandol** [comment]
Updating to V0.17 syntax, `var tmp` has fixed this problem, feel free to close it...

**Comment by zzamboni** [comment]
Thanks!
