### ISSUE TITLE
Timestamp segment in chain theme defaults to grey which is no longer valid 

### ISSUE THREAD

**Issue by vendion** [zzamboni/elvish-themes#6]
By default the `timestamp` segment is set to be colored as "grey" as per this line https://github.com/zzamboni/elvish-themes/blob/master/chain.elv#L45 but with Elvish 0.13 (and presumably going forward) "grey" is no longer a valid color for `styled` command:

```
[/u/h/v/ports]─[⎇ master]─> styled "this message should be red" red
▶ (styled (styled-segment this message should be red &fg-color=<unknown red> &bg-color=$nil))
[/u/h/v/ports]─[⎇ master]─> styled "this message should be grey" grey
Exception: grey is not a valid style transformer
```
The default color for this segment should be updated to be one of the other valid colors, probably "bright-black" instead as that is the closest parallel per the release notes https://elv.sh/blog/0.13-release-notes.html

**Comment by zzamboni** [comment]
@vendion Fixed - thanks for the report!
