### ISSUE TITLE
Add feature for modifying function prompt-segment output

### ISSUE THREAD

**Issue by krader1961** [zzamboni/elvish-themes#7]
I find a prompt with spaces around the segments (imagine the segments being colored differently), ` ~/p/3/elvish  ⎇ min-max-functions >`, easier to read compared to brackets, `[~/p/3/elvish][⎇ min-max-functions]>`. Any chance you would entertain adding a var, such as `chain:segment-brackets = $true`, that `fn prompt-segment` can check for whether to use brackets or spaces. I don't think there is much value in making each char individually configurable as there is really only one other sensible option, `{segment}`, if you ignore non-ASCII characters.

**Comment by zzamboni** [comment]
Thanks for the suggestion!

You can now change the segment delimiters from the default square brackets
by assigning a new value to `$chain:prompt-segment-delimiters`. Its
value can be a two-character string (for single-character delimiters)
or a two-element list (for multi-character or empty
delimiters). Examples:

    chain:prompt-segment-delimiters = "{}"          # {segment}
    chain:prompt-segment-delimiters = "  "          #  segment
    chain:prompt-segment-delimiters = [ "<<" ">>" ] # <<segment>>
    chain:prompt-segment-delimiters = [ "" "" ]     # segment
