### ISSUE TITLE
Bug in fn prompt-segment

### ISSUE THREAD

**Issue by krader1961** [zzamboni/elvish-themes#8]
I implemented support for my Anaconda virtual environment management functions. That involved modifying my prompt to insert a lambda into `chain:prompt-segments`:

```
# This is the default prompt definition but with the addition of a segment to
# report whether I have activated an Anaconda environment.
fn conda-segment []{
  if (not (eq "" $E:CONDA_DEFAULT_ENV)) {
    chain:prompt-segment conda-env $E:CONDA_DEFAULT_ENV
  }
}
chain:prompt-segments = [
  su $conda-segment~ dir git-branch git-combined arrow
]
```

I added  a`git-branch` key to my definition of the `chain:segment-style` map. However, that results in an exception because that segment-style isn't defined by `chain:default-segment-style`. The bug is that this line should use `$segment-style` rather than `$default-segment-style` and `$glyph` rather than `$default-glyph`:

https://github.com/zzamboni/elvish-themes/blob/1010ade24d1dee0a9b62506cfa86298158cac70f/chain.elv#L105-L110

**Comment by krader1961** [comment]
However, note that the code is schizophrenic. The `-glyph` and `-segment-style` functions also check for whether the key is defined in the user modifiable or default maps. So the check in `prompt-segment` that the key exists only in the default maps is objectively wrong. It seems to me the test for whether the `segment-or-style` argument to `prompt-segment` should be directly testing whether the arg is a simple string (i.e., a "segment") or a style argument. It should not be testing whether the value exists in the default segment/glyph maps.

**Comment by krader1961** [comment]
Wouldn't it make more sense to initialize vars like `prompt-segment` when the module is loaded and require the user to modify individual entries rather than assign a new map to the var? That is, require the user do something like this:

```
chain:segment-style[dir] = [bg-bright-green fg-black]
chain:segment-style[git-branch] =  [bg-bright-magenta fg-black]
chain:segment-style[chain] =       [default]
chain:segment-style[arrow] =       [bg-bright-cyan]
chain:segment-style[conda-env] =   [bg-'#DDDDDD' fg-magenta]
```

Rather than this:

```
chain:segment-style = [
  &dir=          [bg-bright-green fg-black]
  &git-branch=   [bg-bright-magenta fg-black]
  &chain=        [default]
  &arrow=        [bg-bright-cyan]
  &conda-env=    [bg-bright-green fg-magenta]
]
```

**Comment by zzamboni** [comment]
@krader1961 I have fixed the checks for `segment-style` and `glyph`.

I don't understand your last comment. Your can define the values any way you want! You can define the whole map for all the styles, or individual values as in the second example.

The logic for both segment styles and glyphs is (now, after this fix):

- If a definition exists in `segment-style`/`glyph`, use that.
- Else, use the definition from `default-segment-style`/`default-glyph`.

**Comment by krader1961** [comment]
@zzamboni The problem was that prior to your commit 8b0c3d2 only the default style map was checked. So when I defined a custom segment name in the current style map it caused an exception since the name didn't exist in the default style map. Your current approach is fine. I was simply musing that if you had a single style map things would be simpler.
