### ISSUE TITLE
Two races in the chain theme

### ISSUE THREAD

**Issue by krader1961** [zzamboni/elvish-themes#9]
Note that the left and right prompts are rendered in parallel in separate goroutines. This causes two data races in the chain theme.

The first is in the `gitstatus:query` function which starts `gitstatusd` if it isn't already running. Since `gitstatus:query` is always run in both prompts via the  `chain:-parse-git` function both prompts can decide that the daemon isn't running and start it. One of those daemons will die almost immediately resulting in this error appearing in the terminal:

```
job (external $binary) \                                                                                                            WTF
        --num-threads=(thread-count) \
        --max-num-staged=$E:GITSTATUS_MAX_NUM_STAGED\
        --max-num-unstaged=$E:GITSTATUS_MAX_NUM_UNSTAGED\
        --max-num-untracked=$E:GITSTATUS_MAX_NUM_UNTRACKED\
        --max-num-conflicted=$E:GITSTATUS_MAX_NUM_CONFLICTED\
        < $state[stdin] \
        > $state[stdout] \
        2> /dev/null & finished
```

The fix is to call `gitstatus:start` right after the `use github.com/href/elvish-gitstatus/gitstatus` statement.

The second race is due to always calling `chain:-git-parse` even if the prompt does not contain any git segments. That can cause the left and right prompts to read from the `gitstatusd` pipe at the same time. Resulting in stochastic exceptions. Properly fixing this will require an Elvish mutex that can be used to protect critical sections. Or a major redesign of the chain module to ensure `-git-parse` is only run once whenever prompts are rendered. A partial fix is to call `-git-parse` only if the prompt contains at least one git segment. That is probably "good enough" since people won't normally put git information in both prompts. This is what my copy of `chain:-build-chain` looks like:

```
fn -build-chain [segments]{
  if (eq $segments []) {
    return
  }
  for seg $segments {
    if (str:has-prefix (to-string $seg) "git-") {
      -parse-git
      break
    }
  }
  first = $true
  output = ""
```

**Comment by zzamboni** [comment]
@krader1961 thanks for the report - I had never noticed the first race condition since I don't use a right-side prompt :)

I agree with your proposed solution, so I have added it to the module. I think this might also be "good enough" without calling `gitstatus:start` after load, since this would also need to check if any git segments are present, and it might still miss if the segments are changed afterwards. Assuming git segments are only on one side, then the new check in `-build-chain` will also ensure `gitstatus` is only started once.

I would appreciate your feedback if you continue to see some problems.

**Comment by krader1961** [comment]
I updated to the current version a few minutes ago and things look good. No unexpected exceptions and the new `chain:prompt-segment-delimiters` var works fine.

**Comment by zzamboni** [comment]
@krader1961 I was thinking that if someone wanted to have git segments on both sides, you could work around the issue by manually starting `gitstatusd` after loading the theme, e.g:
```
use github.com/zzamboni/elvish-themes/chain
chain:gitstatus:start
```
I am going to document this, in case anyone encounters this issue.
